version: '3'
services:
  odoo:
    container_name: odoo
    image: opago/odoo:testing
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: odoo -d db
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
